### ISSUE TITLE
Password match

### ISSUE THREAD

**Issue by Keust** [jagroop/slim3-auth#1]
Hi Jagroop,

The 'matchesPassword' is only to check if the password that is entered is the correct one before changing it to a new one - if i am correct? I assumed it was to verify passwords (two fields the same passw).

I also tried to build an password confirmation. Did you did this already succesfully? Because I really don't know enough and how to start this.

Kind regards,
Keust

**Comment by jagroop** [comment]
Hi @Keust

**Comment by jagroop** [comment]
hi @Keust 

yes you are right the 'matchesPassword' is only to check if the password that is entered is the correct one before changing it to a new one.

No i haven't created such function for password confirmation.

**Comment by jagroop** [comment]
@Keust Have a look at [GUMP validator](https://github.com/Wixel/GUMP)
